Improve missing arguments output.
Now it will explain the arguments are missing and then print the
`--help` text.

Previously;
```
tansell@tansell:~/github/SymbiFlow/fpga-tool-perf$ python3 fpgaperf.py
Traceback (most recent call last):
  File "fpgaperf.py", line 882, in <module>
    main()
  File "fpgaperf.py", line 875, in main
    assert args.toolchain is not None, 'toolchain required'
AssertionError: toolchain required
```

Now;
```
tansell@tansell:~/github/SymbiFlow/fpga-tool-perf$ python3 fpgaperf.py

--toolchain argument required
--project argument required

usage: fpgaperf.py [-h] [--verbose] [--overwrite] [--family FAMILY]
                   [--device DEVICE] [--package PACKAGE] [--strategy STRATEGY]
                   [--toolchain TOOLCHAIN] [--list-toolchains]
                   [--project PROJECT] [--list-projects] [--seed SEED]
                   [--list-seedable] [--check-env] [--out-dir OUT_DIR]
                   [--out-prefix OUT_PREFIX] [--pcf PCF]
```

Signed-off-by: Tim 'mithro' Ansell <me@mith.ro>